spring:
  application:
    name: cart-service
  profiles:
    default: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
  instance:
    preferIpAddress: true

server:
  port: 19096

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0